#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet

#- If running parallel
# nProc=$(getNumberOfProcessors)
# runApplication decomposePar
# ls -d processor* | xargs -I {} rm -rf ./{}/0
# ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
# runParallel pimpleFoam $nProc 
# runParallel vorticity  $nProc

#- If running serial
pimpleFoam | tee log.pimpleFoam
runApplication vorticity

#- If running parallel
# runApplication reconstructPar

python scripts/gensampledict.py
runApplication sample
