#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet
runApplication setFields

if [ "$1" = "-parallel" ]
    then
    nProc=$(getNumberOfProcessors)
    runApplication decomposePar
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
    runParallel $(getApplication)  $nProc
    runApplication reconstructPar
else
    runApplication $(getApplication)
fi

runApplication vorticity
scripts/Allrun.post
